version: '3'
services:
  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    environment:
      - JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Advertising test container
  advertise-test:
    build: ./ble_advertise_test
    container_name: advertise_test
    volumes:
      - ./ble_advertise_test:/usr/src/ble_advertise_test
    depends_on:
      - jenkins
    restart: on-failure

  # Receiving test container
  receive-test:
    build: ./ble_receive_test
    container_name: receive_test
    volumes:
      - ./ble_receive_test:/usr/src/ble_receive_test
    depends_on:
      - jenkins
    restart: on-failure

  # Sending test container
  send-test:
    build: ./ble_sending_test
    container_name: send_test
    volumes:
      - ./ble_sending_test:/usr/src/ble_sending_test
    depends_on:
      - jenkins
    restart: on-failure

  # Sensor test container
  sensor-test:
    build: ./ble_sensor_test
    container_name: sensor_test
    volumes:
      - ./ble_sensor_test:/usr/src/ble_sensor_test
    depends_on:
      - jenkins
    restart: on-failure

volumes:
  jenkins_home:

